image: microsoft/dotnet:2.1-sdk

stages:
- build
- test
- pack
- nuget

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --no-restore -c Debug
  artifacts:
    untracked: true
    expire_in: 6 hours

test:
  stage: test
  script:
    - dotnet restore
    - (cd src/MBW.Utilities.IPAddresses.Tests; dotnet test -c Debug /p:CollectCoverage=true)
  dependencies:
  - build

benchmark-ipv4:
  stage: test
  script:
    - dotnet restore
    - (cd src/MBW.Utilities.IPAddresses.Benchmarks; dotnet run -c RELEASE -- -f ParseIPv4Strategies)
  dependencies:
  - build

benchmark-ipv6:
  stage: test
  script:
    - dotnet restore
    - (cd src/MBW.Utilities.IPAddresses.Benchmarks; dotnet run -c RELEASE -- -f ParseIPv6Strategies)
  dependencies:
  - build

pack:
  stage: pack
  script:
    - dotnet restore
    - dotnet pack -c Release --no-restore -o $CI_PROJECT_DIR/Build
  artifacts:
    paths:
    - Build/*.nupkg
    expire_in: 1 week
  dependencies:
  - build

nuget:
  stage: nuget
  script:
    - dotnet nuget push Build/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_KEY
  dependencies:
  - pack
  only:
  - nuget