name: .NET

on:
  push:
    branches: [ master, nuget ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack
      run: dotnet pack -o Build/
    - name: Store artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: package
        path: Build/

  nuget:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: nuget
      
    if: github.ref == 'refs/heads/nuget'

    steps:
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_KEY }}
        nuget-version: latest
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: package
    - name: Publish
      run: nuget push Build/*.nupkg -SkipDuplicate